### ISSUE TITLE
Reporting plugin does not work

### ISSUE THREAD

**Issue by webwurst** [giantswarm/efk-stack-app#53]
When trying to generate a report Kibana puts out this error message:
> Download error - There was an error generating this report.

The underlying error message from the API might be this:
```json
{"statusCode":500,"error":"Internal Server Error","message":"Cannot read property 'settings' of undefined"}
```

Upstream [pull request is already merged](https://github.com/opendistro-for-elasticsearch/kibana-reports/pull/267), so this should be included in the next release.

**Comment by cokiengchiara** [comment]
Moving to backlog as it will be handled here https://github.com/giantswarm/roadmap/issues/272#issuecomment-783514069 pls correct if wrong @webwurst

**Comment by piontec** [comment]
ping @webwurst

**Comment by snizhana-dynnyk** [comment]
seems like it is fixed
