### ISSUE TITLE
kube-linter is not happy (EFK)

### ISSUE THREAD

**Issue by webwurst** [giantswarm/efk-stack-app#63]
Run `kube-linter lint ./helm/efk-stack-app` for more details.

Overview of possible fixes:
- [ ] helm/efk-stack-app/charts/opendistro-es/templates/elasticsearch/es-data-sts.yaml
  - container "elasticsearch"
    - check: drop-net-raw-capability
    - check: no-read-only-root-fs
    - check: run-as-non-root
    - check: unset-cpu-requirements
    - check: unset-cpu-requirements
    - check: unset-memory-requirements
    - check: unset-memory-requirements
- [ ] helm/efk-stack-app/charts/fluentd-elasticsearch/templates/daemonset.yaml
  - container "test-release-fluentd-elasticsearch" 
    - check: no-read-only-root-fs
    - check: run-as-non-root
    - check: unset-cpu-requirements
    - check: unset-cpu-requirements
    - check: unset-memory-requirements
    - check: unset-memory-requirements
- [ ] helm/efk-stack-app/charts/opendistro-es/templates/elasticsearch/es-client-deploy.yaml
  - container "elasticsearch"
    - check: drop-net-raw-capability
    - check: no-read-only-root-fs
    - check: run-as-non-root
    - check: unset-cpu-requirements
    - check: unset-cpu-requirements
    - check: unset-memory-requirements
    - check: unset-memory-requirements
- [ ] helm/efk-stack-app/charts/elasticsearch-curator/templates/cronjob.yaml
  - container "elasticsearch-curator" 
    - check: no-read-only-root-fs
    - check: unset-cpu-requirements
    - check: unset-cpu-requirements
    - check: unset-memory-requirements
    - check: unset-memory-requirements
- [ ] helm/efk-stack-app/charts/opendistro-certs/templates/job.yaml
  - container "certs" 
    - check: no-read-only-root-fs   
    - check: run-as-non-root    
    - check: unset-cpu-requirements 
    - check: unset-cpu-requirements 
    - check: unset-memory-requirements  
    - check: unset-memory-requirements  
    - check: no-read-only-root-fs   
    - check: run-as-non-root    
    - check: unset-cpu-requirements 
    - check: unset-cpu-requirements 
    - check: unset-memory-requirements  
    - check: unset-memory-requirements
- [ ] helm/efk-stack-app/charts/opendistro-es/templates/kibana/kibana-deployment.yaml
  - container "test-release-opendistro-es-kibana" 
    - check: no-read-only-root-fs
    - check: run-as-non-root
    - check: unset-cpu-requirements
    - check: unset-cpu-requirements
    - check: unset-memory-requirements
    - check: unset-memory-requirements
  - serviceAccount "test-release-opendistro-es-kibana"
    - check: non-existent-service-account
- [ ] helm/efk-stack-app/charts/opendistro-es/templates/elasticsearch/es-master-sts.yaml
  - container "elasticsearch"
    - check: drop-net-raw-capability
    - check: no-read-only-root-fs
    - check: run-as-non-root
    - check: unset-cpu-requirements
    - check: unset-cpu-requirements
    - check: unset-memory-requirements
    - check: unset-memory-requirements
- [ ] helm/efk-stack-app/charts/elasticsearch-exporter/templates/deployment.yaml
  - container "elasticsearch-exporter" 
    - check: unset-cpu-requirements
    - check: unset-cpu-requirements
    - check: unset-memory-requirements
    - check: unset-memory-requirements

Also see https://github.com/giantswarm/efk-stack-app/pull/14 for ideas.

**Comment by cokiengchiara** [comment]
- what is the benefit? Security. Memory. Planning your clusters better.
- It's very costly to check everything to make this work.
- Nice to have
- It's sth for upstream.

**Comment by snizhana-dynnyk** [comment]
no plans to do this now, we will open if this comes back
