### ISSUE TITLE
Replace opendistro-certs by cert-manager certificates

### ISSUE THREAD

**Issue by webwurst** [giantswarm/efk-stack-app#65]
At the moment we are using a [script to create the initial certificates](https://github.com/giantswarm/opendistro-certs/blob/master/generate_certs.sh) with a validity of 5 years by default. We don't have any process to renew those when expired.

Promising example for using cert-manager certificates instead: https://github.com/opendistro-for-elasticsearch/security/issues/52#issuecomment-785024286

Maybe also follow https://github.com/kubernetes/ingress-nginx/issues/6666#issuecomment-751799274 for discussion and insights.

**Comment by cokiengchiara** [comment]
Dupe with: https://github.com/giantswarm/roadmap/issues/199

Is this still relevant considering https://github.com/giantswarm/roadmap/issues/294?

**Comment by webwurst** [comment]
Right, this is a duplicate. But the links are helpful.
